### ISSUE TITLE
orientation vector of attachment nodes is incorrect in length or direction.

### ISSUE THREAD

**Issue by Alewx** [girka2k/UbioWeldContinued#12]
with the curent orientation mergeing the node is getting a strange vector that is not equal one or completly in a wrong direction.

**Comment by Alewx** [comment]
SPH symmetry mode is providing Problems for the attachnode roration, this fix should be included.

**Comment by girka2k** [comment]
Now length is normalized:
518249457d6f7283b095035c69c9f1642563c581

**Comment by girka2k** [comment]
I think it's fixed in 518249457d6f7283b095035c69c9f1642563c581 and fc62fed37da7dae05fb8283bd13d6f2cb1fe279b
