### ISSUE TITLE
enhance Database reload to work with ModuleManager.

### ISSUE THREAD

**Issue by Alewx** [girka2k/UbioWeldContinued#14]
the current pure database reload after welding parts would atleast break parts that are modified by MM files, if not more plugins.
There should be an possibility to enhance the reload of the database to use MM updates.

**Comment by Alewx** [comment]
done in https://github.com/Alewx/unofficailUbioWeld/commit/cbab1408fd856a3ade8dbfa8209efa30c4f6592c

**Comment by girka2k** [comment]
Great!
