### ISSUE TITLE
IO sharing exception after loading the scene and trying to weld something

### ISSUE THREAD

**Issue by Alewx** [girka2k/UbioWeldContinued#21]
suddenly after you load the Scene and try to weld something in a relative short time you get an io sharing exception as you try to use the "weld it" button in the main window.
My Suggestion is that the file is still reading the config while it already tries to save the config before the part is welded, changing this work list might help or changing the filestreamwriter/Reader.

**Comment by girka2k** [comment]
Done!
9edeab6a828eb5de10e8c17284ea586ae1b52ea6
