### ISSUE TITLE
In MainWindow add selectors for StrengthCalcMethod and MaxTempCalcMethod settings

### ISSUE THREAD

**Issue by girka2k** [girka2k/UbioWeldContinued#24]

**Comment by Alewx** [comment]
maybe an additional explanaition of what changes with the different methods?

**Comment by girka2k** [comment]
I think it will be enough short description in hint area.
Details can be published on the forum and be attached in the form of a readme file

**Comment by Alewx** [comment]
That is exactly what I meant :) perfect

**Comment by girka2k** [comment]
8812e0c7660a210300f12385fb4a006efe860f81
Minimized window:
![2014-10-17 21-43-29 kerbal space program](https://cloud.githubusercontent.com/assets/6450733/4683287/41f801b8-5625-11e4-9029-b4e6dc69406a.png)
With settings:
![2014-10-17 21-44-15 kerbal space program](https://cloud.githubusercontent.com/assets/6450733/4683290/4e1f0572-5625-11e4-93dc-f78174b88e68.png)
