### ISSUE TITLE
Configsave fix breaks welding

### ISSUE THREAD

**Issue by girka2k** [girka2k/UbioWeldContinued#26]
The commit https://github.com/girka2k/unofficailUbioWeld/commit/1f54c62385515a03351b2a7869eda9d7f272a98c makes it impossible to weld anything.
In Filemanager.cs the assignment operator "WeldingConfiguration configuration = configToSave;" is not copying of the object, but copying of the reference to object, so the following operations are performed also with the original object.
As result - exception in mergeModulesAlexTest in line
if (!WeldingHelpers.isArrayContaing(newModuleName, UbioZurWeldingLtd.instance.config.modulesToIgnore))

**Comment by girka2k** [comment]
temporary fix: 7af22a953b99b3d76190e53073a39c647e6f3333

**Comment by girka2k** [comment]
Perhaps a good and simple solution would be to refuse the use of the file moduleAttributeList.xml and to keep everything in new-config.xml

**Comment by Alewx** [comment]
A second saving method for this might be good it could clean up the config and then save it.
That would fix the problem.

**Comment by Alewx** [comment]
done in 
https://github.com/girka2k/unofficailUbioWeld/commit/6ba6fc76133e7112de66612f87b31c03d9d96404

**Comment by girka2k** [comment]
Not sure I understand the proposed changes in https://github.com/girka2k/unofficailUbioWeld/commit/6ba6fc76133e7112de66612f87b31c03d9d96404
Probably you mean something like this:

```
    public static void saveConfig(WeldingConfiguration configToSave, bool saveModuleListConfig)
    {
        WeldingConfiguration configuration = (WeldingConfiguration)configToSave.clone();
        ModuleLists moduleList = new ModuleLists();
        TextWriter fileStreamWriter;
        if (configuration == null)
        {
            configuration = new WeldingConfiguration();
        }

        configuration.vector2CurveModules = null;
                    //some lines skipped here----------------------------------------------------------------------
        configuration.breakingModuleAttributes = null;
        if (saveModuleListConfig)
        {
            moduleList.vector2CurveModules = WeldingHelpers.convertStringFromToArray(Constants.basicVector2CurveModules);
                    //some lines skipped here----------------------------------------------------------------------
            moduleList.breakingModuleAttributes = WeldingHelpers.convertStringFromToArray(Constants.basicBreakingModuleAttributes);

            XmlSerializer moduleListSerializer = new XmlSerializer(typeof(ModuleLists));
            fileStreamWriter = new StreamWriter(_moduleListFile);
            moduleListSerializer.Serialize(fileStreamWriter, moduleList);

            foreach (string s in comments)
            {
                fileStreamWriter.WriteLine(s);
            }
            fileStreamWriter.Close();
        }

        XmlSerializer configSerializer = new XmlSerializer(typeof(WeldingConfiguration));
        fileStreamWriter = new StreamWriter(_configFile);
        configSerializer.Serialize(fileStreamWriter, configuration);
        fileStreamWriter.Close();
    }
```

?

**Comment by Alewx** [comment]
Looks like a shorter and simpler Version than I did.

**Comment by girka2k** [comment]
this variant will always be to clean the properties associated with the modules, and when saveModuleListConfig is "True" to create the file moduleAttributeList.xml

**Comment by Alewx** [comment]
Sounds good to me, if you already tested it, there is no Problem.

**Comment by girka2k** [comment]
STOP. Now I don't understand my variant also :)
Why do we need this new bool parameter anyway? Wouldn't it be easier to always overwrite the file moduleAttributeList.xml?

**Comment by girka2k** [comment]
By the way, the trick with MemberwiseClone I really liked - I didn't know about this method

**Comment by Alewx** [comment]
yes but, the ModuleAttributelist.xml was not really the Problem, the error was that it was saving the modulelist into the config.xml

**Comment by girka2k** [comment]
Then it seems to me that all you need is change line
    WeldingConfiguration configuration = configToSave;
from your 1f54c62385515a03351b2a7869eda9d7f272a98c
to
    WeldingConfiguration configuration = (WeldingConfiguration)configToSave.clone();
and add the appropriate method "clone()" to WeldingConfiguration class

**Comment by Alewx** [comment]
ok now I got it, and made it keeping user entries.
https://github.com/Alewx/unofficailUbioWeld/commit/d385ea84b9049b535f8e20aaaeb2f41dfe276595
