### ISSUE TITLE
Database Reload is heavy bound to referenced version of ModuleManager

### ISSUE THREAD

**Issue by Alewx** [girka2k/UbioWeldContinued#28]
the current implementation of the database reload is heavy bound to the referenced Version of ModuleManager, this results in FileNotFoundException:  exception.

Suggestion is to just reference the very last updated Version of MM

**Comment by Alewx** [comment]
A Version check ob the installed and referenced Modulemanager would be great.

**Comment by girka2k** [comment]
I did temporary stub for it - e48f97c04db4f963422feaf5f7491478d810844b
I added a switch (reloadDbUsingMM) to specify whether to use ModuleManager for the DB reload (this setting is hidden from GUI and disabled by default; can be changed in config file only)

**Comment by Alewx** [comment]
ok, that should do it until we found a solution for version controlling.

**Comment by girka2k** [comment]
I guess it's done
a8ec0471822e9207f4ab82faf7fe5eafab75050c
