### ISSUE TITLE
Probably, it is needed to reset values less than 1e-6, especially in the orientation of the nodes

### ISSUE THREAD

**Issue by girka2k** [girka2k/UbioWeldContinued#40]

**Comment by girka2k** [comment]
Looked at the UNITY's definition of the class Vector3.

```
public struct Vector3
{
    public const float kEpsilon = 1e-005f;

    public float x;
    public float y;
    public float z;
    ------
}
```

It seems to me that the constant kEpsilon = 1e-005f here for a reason. Probably we should round values up to 5 characters, not 6

**Comment by Alewx** [comment]
Ok, we can do that.
Do you have an idea how you want to round them?
What I got so far was to convert it into a toString(0:f6) and then cast/parse back into float.

**Comment by girka2k** [comment]
I hope this would work (hasn't tested it yet!) acc451f6dd27e77417ee9c37b2d33f38f1a82bbe

```
    public static Vector3 RoundVector3(Vector3 inVector)
    {
        float x = (float)Math.Round(inVector.x, Constants.weldNumberOfFractionalDigits);
        float y = (float)Math.Round(inVector.y, Constants.weldNumberOfFractionalDigits); ;
        float z = (float)Math.Round(inVector.z, Constants.weldNumberOfFractionalDigits); ;
        return new Vector3(x, y, z);
    }
```

**Comment by Alewx** [comment]
I believe that the double semicolon might cause problems.

float y = (float)Math.Round(inVector.y, Constants.weldNumberOfFractionalDigits); ;
float z = (float)Math.Round(inVector.z, Constants.weldNumberOfFractionalDigits); ;

**Comment by girka2k** [comment]
actually no, it is perceived as "empty" operator by compiler (of course, I compiled it, just can't try it out), but Yes, it was a typo, of course

**Comment by girka2k** [comment]
Yes, it's seems to work!
Rounds most values to 5 fractional digits b9c88977105c68aef0e3e736678f45776a70cb39

**Comment by Alewx** [comment]
Most? does it leave some unchanged, incase they are vectors?

**Comment by girka2k** [comment]
It rounds all componets of nodes & model's positions (i.e. vectors) and model's rotations, crashTolerance, breakingForce, breakingTorque, maxTemp, maximum_drag, minimum_drag.
In short everything except the amount of resources.

**Comment by girka2k** [comment]
PART
{
    name = weldedpart3sym4
    module = Part
    author = UbioZurWeldingLtd
    rescaleFactor = 1
    PhysicsSignificance = -1
    node_stack_topmk1pod0 = 0,3.08987,0,0,1,0,0
    node_stack_bottomfuelTank.long1 = 0,-1.72005,0,0,0.125,0,1
    node_stack_topfuelTank.long2 = -1.14731,1.66689,-0.50345,0,0.125,0,1
    node_stack_bottomfuelTank.long2 = -1.14731,-2.09561,-0.50345,0,0.125,0,1
    node_stack_topfuelTank.long3 = 0.13766,1.66689,1.24532,0,0.125,0,1
    node_stack_bottomfuelTank.long3 = 0.13766,-2.09561,1.24532,0,0.125,0,1
    node_stack_topfuelTank.long4 = 1.00965,1.66689,-0.74188,0,0.125,0,1
    node_stack_bottomfuelTank.long4 = 1.00965,-2.09561,-0.74188,0,0.125,0,1
    node_attach = 0,0,0,0,0,0,0
    CrewCapacity = 1
    TechRequired = start
    entryCost = 19200
    cost = 7000
    category = Propulsion
    subcategory = 0
    title = weldedpart3sym4
    manufacturer = UbioZur Welding Ltd
    description = Warranty void during re-entry.
    attachRules = 1,1,1,1,0,0,0
    mass = 2.8
    dragModelType = default
    maximum_drag = 0.19375
    minimum_drag = 0.28594
    angularDrag = 1.9375
    crashTolerance = 8.28571
    breakingForce = 42
    breakingTorque = 42
    maxTemp = 2900
    fuelCrossFeed = True
    MODEL
    {
        model = Squad/Parts/Command/mk1pod/model
        position = 0,2.44749,0
        scale = 1,1,1
        rotation = 0,0,0
    }
    MODEL
    {
        model = Squad/Parts/FuelTank/fuelTankT800/model
        position = 0,0.16745,0
        scale = 1.25,1.25,1.25
        rotation = 0,0,0
    }
    MODEL
    {
        model = Squad/Parts/FuelTank/fuelTankT800/model
        position = -1.14731,-0.20811,-0.50345
        scale = 1.25,1.25,1.25
        rotation = 360,330.0001,0
    }
    MODEL
    {
        model = Squad/Parts/FuelTank/fuelTankT800/model
        position = 0.13766,-0.20811,1.24532
        scale = 1.25,1.25,1.25
        rotation = 360,90.00006,0
    }
    MODEL
    {
        model = Squad/Parts/FuelTank/fuelTankT800/model
        position = 1.00965,-0.20811,-0.74188
        scale = 1.25,1.25,1.25
        rotation = 360,210.0001,0
    }
    RESOURCE
    {
        name = ElectricCharge
        amount = 50
        maxAmount = 50
    }
    RESOURCE
    {
        name = MonoPropellant
        amount = 10
        maxAmount = 10
    }
    RESOURCE
    {
        name = LiquidFuel
        amount = 1440
        maxAmount = 1440
    }
    RESOURCE
    {
        name = Oxidizer
        amount = 1760
        maxAmount = 1760
    }
    MODULE
    {
        name = ModuleCommand
        minimumCrew = 1
    }
    MODULE
    {
        name = ModuleSAS
    }
    MODULE
    {
        name = ModuleReactionWheel
        PitchTorque = 5
        YawTorque = 5
        RollTorque = 5
        RESOURCE
        {
            name = ElectricCharge
            rate = 0.24
        }
    }
    MODULE
    {
        name = ModuleScienceExperiment
        experimentID = crewReport
        experimentActionName = Crew Report
        resetActionName = Discard Crew Report
        reviewActionName = Review Report
        useStaging = False
        useActionGroups = True
        hideUIwhenUnavailable = True
        rerunnable = True
        xmitDataScalar = 1.0
    }
    MODULE
    {
        name = ModuleScienceContainer
        reviewActionName = Review Stored Data
        storeActionName = Store Experiments
        evaOnlyStorage = True
        storageRange = 1.3
    }
    MODULE
    {
        name = FlagDecal
        textureQuadName = flagTransform
    }
}

**Comment by Alewx** [comment]
Looks good to me.
Didn't say anything ;)
