### ISSUE TITLE
crashTolerance, breakingForce and breakingTorque calculations must be fixed

### ISSUE THREAD

**Issue by girka2k** [girka2k/UbioWeldContinued#5]
At this moment crashTolerance, breakingForce and breakingTorque values looks ridiculously big - bigger than values of constituent parts.

**Comment by girka2k** [comment]
may be weighted average by mass of parts?

**Comment by Alewx** [comment]
That sounds logical to me.
Maybe a switch in the config like for the temperature?

**Comment by girka2k** [comment]
Yes. Switch would be good. By the way, yesterday I tested calculations of these params as weighted average by mass of parts and was satisfied. 
I have only to add the correct treatment for massless parts, but it will be on Monday

**Comment by girka2k** [comment]
done
https://github.com/girka2k/unofficailUbioWeld/commit/368072f907bbc2410bdbf6e18afa3216638a7a46
