### ISSUE TITLE
The presence of a config.xml file in the old format does not allow the module to start

### ISSUE THREAD

**Issue by girka2k** [girka2k/UbioWeldContinued#6]
After changing the file format of config.xml the presence of old one does not allow the module to start.
Possible solution - use other name for new-style config

**Comment by Alewx** [comment]
Startet working on this.

**Comment by Alewx** [comment]
done in https://github.com/Alewx/unofficailUbioWeld/commit/147d1e966845bbecb3c0d22f4010ebe8824abc22

**Comment by girka2k** [comment]
Alewx, are you sure it's needed to read the old config?
The default settings are good, and near future I hope to make a minimalistic GUI with the ability to change them

**Comment by Alewx** [comment]
The old config will be read once and then deleted, while the values are transfered into the new config.
Done in https://github.com/Alewx/unofficailUbioWeld/commit/147d1e966845bbecb3c0d22f4010ebe8824abc22
