### ISSUE TITLE
Make additional GUI with possibility to change (and save) base settings

### ISSUE THREAD

**Issue by girka2k** [girka2k/UbioWeldContinued#7]

**Comment by girka2k** [comment]
At the moment it's something like this:
![2014-10-02 10-18-16 kerbal space program](https://cloud.githubusercontent.com/assets/6450733/4487470/34fdf9b6-49fc-11e4-8e5f-3c4c1ec57eb6.png)

**Comment by Alewx** [comment]
That is damn nice Information below.
How shall the user access it? extra button, or changing the button state?

**Comment by girka2k** [comment]
This window appears when you click button on stock Toolbar.
Now it is like this: (here's a typo - the button labeled "Use named part's file" actually is "Save settings" button) ![2014-10-02 13-46-31 kerbal space program](https://cloud.githubusercontent.com/assets/6450733/4489338/c265fd86-4a19-11e4-8b39-b5b4059c7d8f.png)

**Comment by Alewx** [comment]
Ok cool, does it still work with the selected part in case you do not want to weld the whole craft?
Then we can remove the old weld button.

**Comment by girka2k** [comment]
this will not be a problem - I would only have to add your commits.
Later I will clean up this code if you don't mind.

**Comment by Alewx** [comment]
ok, no, I have no problem with it.

**Comment by girka2k** [comment]
Final draft variant https://github.com/girka2k/unofficailUbioWeld/commit/267aa12f14770d65e0ae9fffc98b91c27dd8cdd5 . The window pops up by pressing the stock toolbar button.
![2014-10-07 12-12-07 kerbal space program](https://cloud.githubusercontent.com/assets/6450733/4539148/c7ff6050-4df9-11e4-900c-013d9b6b13fd.png)

**Comment by Alewx** [comment]
I prefer this format, do you want to include the windowsize also in the settings?

**Comment by girka2k** [comment]
Windowsize? No, and I dont' think it's needed.
The position on the screen - yes, it should be done.

**Comment by girka2k** [comment]
Now with main window position saving:
https://github.com/girka2k/unofficailUbioWeld/commit/bf29643088e3580cd2edbc8eb92e5a8570bd3f88
