### ISSUE TITLE
change the scaling of the parts to be read from the ones that are currently in the scene

### ISSUE THREAD

**Issue by girka2k** [girka2k/UbioWeldContinued#9]
change the scaling of the parts to be read from the ones that are currently in the scene, as that would fix also tweakscale stuff, and include configurations that were made in the game that are not contained in the configfile.

**Comment by Alewx** [comment]
Looking into this.

**Comment by Alewx** [comment]
done in https://github.com/Alewx/unofficailUbioWeld/commit/fa4c924f526b64ebe5817377ef69d1a452a6ae4c
